#!/bin/sh

# SPDX-FileCopyrightText: 2024 NONE
#
# SPDX-License-Identifier: 0BSD

cd "$(git rev-parse --show-toplevel)" || exit 1

# if version.h exists, regenerate it for the new commit
[ -e version.h ] && ./gen_version_h.sh
