#!/bin/sh

# SPDX-FileCopyrightText: 2024 NONE
#
# SPDX-License-Identifier: 0BSD

cd "$(git rev-parse --show-toplevel)" || exit 1

# if version.h exists, regenerate it for the new commit, otherwise, do nothing.
if [ -e version.h ]; then ./gen_version_h.sh; else exit 0; fi
