#!/bin/sh

# SPDX-FileCopyrightText: 2024 - 2025 Eli Array Minkoff
#
# SPDX-License-Identifier: 0BSD

cd "$(git rev-parse --show-toplevel)" || exit 1

if [ "$(git branch --show-current)" = 'main' ]; then
    make clean all_tests
fi
