#!/bin/sh

# SPDX-FileCopyrightText: 2024 - 2026 Eli Array Minkoff
#
# SPDX-License-Identifier: 0BSD

cd "$(git rev-parse --show-toplevel)" || exit 1

if git status --porcelain | grep -q .; then
    printf 'Uncommitted changes!\n' >&2
    exit 1
fi

make clean test
