#!/bin/sh

# SPDX-FileCopyrightText: 2024 NONE
#
# SPDX-License-Identifier: 0BSD

cd "$(git rev-parse --show-toplevel)" || exit 1

# ensure that the version file is not associated with an existing version
if [ "$(git tag --list "v$(cat version)" | wc -c)" -gt 0 ]; then
    printf 'ERROR! Version file corresponds to an existing tag!\n'
fi

./run-lints.sh
